#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ฉีดบล็อก house-rules ลงหน้าห้องพัก "ภาษาไทย" เท่านั้น (หน้าไทย = ต้นฉบับเสมอ)

หน้า /en และ /lo ห้ามแก้มือ — สร้างจาก tools/build_i18n.py หลังรันสคริปต์นี้

ใช้:
    python3 tools/apply_house_rules.py            # dry-run
    python3 tools/apply_house_rules.py --apply    # เขียนจริง
    python3 tools/build_i18n.py                   # แล้วค่อย build en/lo
"""

import argparse
import pathlib
import re
import sys

BEGIN = "<!-- BEGIN house-rules (generated - edit tools/house-rules.html, not here) -->"
END = "<!-- END house-rules -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)

# หมายเหตุ: marker ต้องเป็นภาษาอังกฤษล้วน — build_i18n.py ตัด comment ที่มีอักษรไทยทิ้ง
ANCHOR = "<footer>"


def inject(html: str, block: str) -> tuple[str, str]:
    wrapped = f"{BEGIN}\n{block}\n{END}"
    if BLOCK_RE.search(html):
        return BLOCK_RE.sub(lambda _: wrapped, html), "updated"
    idx = html.find(ANCHOR)
    if idx == -1:
        return html, "skipped"
    return html[:idx] + wrapped + "\n\n" + html[idx:], "inserted"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=".")
    ap.add_argument("--glob", default="rooms/*/index.html")
    ap.add_argument("--partial", default="tools/house-rules.html")
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    root = pathlib.Path(args.repo).resolve()
    partial = root / args.partial
    if not partial.exists():
        print(f"error: partial not found: {partial}", file=sys.stderr)
        return 1
    block = partial.read_text(encoding="utf-8").strip()

    pages = sorted(root.glob(args.glob))
    if not pages:
        print(f"error: no files matched {args.glob!r} under {root}", file=sys.stderr)
        return 1
    if any(p.parts[len(root.parts)] in ("en", "lo") for p in pages):
        print("error: refusing to touch /en or /lo — those are generated by build_i18n.py",
              file=sys.stderr)
        return 1

    counts = {"updated": 0, "inserted": 0, "skipped": 0, "unchanged": 0}
    for page in pages:
        original = page.read_text(encoding="utf-8")
        new, action = inject(original, block)
        if action == "skipped":
            print(f"  SKIP     {page.relative_to(root)}  — no {ANCHOR} anchor")
        elif new == original:
            action = "unchanged"
            print(f"  same     {page.relative_to(root)}")
        else:
            print(f"  {action.upper():<8} {page.relative_to(root)}")
            if args.apply:
                page.write_text(new, encoding="utf-8")
        counts[action] += 1

    print("\n" + ", ".join(f"{v} {k}" for k, v in counts.items() if v))
    if not args.apply:
        print("dry run — ยังไม่เขียนไฟล์ ใส่ --apply เพื่อเขียนจริง")
    else:
        print("อย่าลืมรัน: python3 tools/build_i18n.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
